### ISSUE TITLE
[device-info] Add touch and native detection

### ISSUE THREAD

**Issue by youzi** [vigour-io/ua#13]
When doing server side rendering we need as much information as we can possibly get from the ua.

For rendering static cases we need to add `native` and `touch`. Maybe we can come up with more interesting fields?

/cc @jimdebeer

**Comment by shawninder** [comment]
@youzi Can you give me an idea of the priority of this? I could start adding fields today if this is urgent...

**Comment by youzi** [comment]
@shawn High priority to find out if it's possible to make this reliable, based on the ua string. If not we need to come up with another solution.

Only fields needed for our current app are: `native` and `touch`.

**Comment by shawninder** [comment]
@youzi Well there is no standard way of indicating whether a device supports touch via its user agent string. The best we could do for this is to make a list of devices we can recognize that are touch-enabled, try to maintain that list as best we can, and accept that this won't work for some more obscure devices... The alternative is feature-detection, but that's clearly not an option for server-side rendering...

**Comment by shawninder** [comment]
First attempt: https://github.com/vigour-io/ua/pull/14
